version: "3.1"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: "bitnami/redis:6.2.14"
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - app-tier

  redis-sentinel:
    image: "bitnami/redis-sentinel:6.2.14"
    container_name: redis-sentinel
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=127.0.0.1
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=primary
      - REDIS_SENTINEL_QUORUM=1  # 마스터 하나만 사용하므로 최소 쿼럼을 1로 설정
    depends_on:
      - redis
    ports:
      - "26379:26379"
    networks:
      - app-tier
